### ISSUE TITLE
I got error E909 when omni func result is `Pattern not found`

### ISSUE THREAD

**Issue by mikoto2000** [thomasfaingnaert/vim-lsp-ultisnips#1] opened 2019-04-15 14:49 UTC
# Problem

I tried ultisnips-integration.(https://github.com/prabirshrestha/vim-lsp/issues/361#issuecomment-480647232)

1. type `book`
2. start omni complete(omni complete result is `Pattern not found`)
3. I got E909 error

![image](https://user-images.githubusercontent.com/345832/56140707-5da14180-5fd6-11e9-8d34-a679ae1218cf.png)

# Cause

I think this error raised when user_data is empty.

https://github.com/thomasfaingnaert/vim-lsp-ultisnips/blob/4bfbda4db6f2dfa723e1366ad5e13ee3038e3b5c/autoload/lsp_ultisnips.vim#L59-L62

# Proposed solution

Take into consideration these pattern.

- user_data contain not json string.
- user_data is empty.

**Comment by thomasfaingnaert** [comment] 2019-04-15 17:12
@mikoto2000 I can indeed reproduce the issue. For me, the branch `fix-e909` fixes it. Can you verify if the issue is fixed on your end as well?

It's interesting that typing the complete match results in a `Pattern not found`. Perhaps we should fix that as well?

**Comment by mikoto2000** [comment] 2019-04-16 13:34
@thomasfaingnaert I tried `fix-e909`, it's worked.

> It's interesting that typing the complete match results in a Pattern not found. Perhaps we should fix that as well?

I want fix it. I think it is vim-lsp issue. I will create issue to vim-lsp.

**Closed as completed** 2019-04-18 17:19 UTC
